#!/usr/bin/env bash
# fetch-fonts.sh — downloads the project's self-hosted webfonts into Shopify/assets/fonts/
# and emits assets/fonts/fonts.css with local @font-face rules.
#
# Fonts are self-hosted so every site in this project renders correctly with no
# internet connection and no CDN round-trip.
#   Run:  bash tools/fetch-fonts.sh
set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/assets/fonts"
mkdir -p "$OUT"
UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'

CSS="$OUT/fonts.css"
{
  echo "/* ==========================================================================="
  echo "   fonts.css — self-hosted webfaces for the whole project."
  echo "   Generated by tools/fetch-fonts.sh. Do not hand-edit; re-run the script."
  echo "   =========================================================================== */"
  echo
} > "$CSS"

# --- Fontshare families (professional-grade, free for commercial use) -------
FONTSHARE=(
  "satoshi@300,400,500,700,900"        # primary neo-grotesque UI sans
  "general-sans@400,500,600,700"       # alt geometric sans
  "switzer@300,400,500,600,700"        # swiss neutral sans
  "cabinet-grotesk@400,500,700,800"    # display grotesk
  "clash-display@400,500,600,700"      # bold display
  "boska@300,400,500,700"              # high-contrast luxury serif
  "gambetta@400,500,600,700"           # refined bookish serif
  "erode@400,500,600,700"              # warm textured serif
  "chillax@300,400,500,600"            # soft rounded sans (playful)
  "sentient@400,500,700"               # editorial serif
  "supreme@400,500,700"                # techy grotesk
)

echo "==> Fontshare"
for spec in "${FONTSHARE[@]}"; do
  fam="${spec%@*}"
  raw=$(curl -sL --max-time 40 -A "$UA" "https://api.fontshare.com/v2/css?f[]=${spec}&display=swap")
  [ -z "$raw" ] && { echo "  !! $fam — no CSS"; continue; }

  # Flatten each @font-face block onto one line so we can parse it with awk.
  n=0
  echo "/* --- $fam ------------------------------------------------------------ */" >> "$CSS"
  echo "$raw" | tr '\n' ' ' | sed 's/@font-face/\n@font-face/g' | grep '@font-face' | while read -r block; do
    url=$(echo "$block"    | grep -oE "(https:)?//cdn\.fontshare\.com/[^')\"]+\.woff2" | head -1)
    family=$(echo "$block" | sed -nE "s/.*font-family: *'([^']+)'.*/\1/p")
    weight=$(echo "$block" | sed -nE "s/.*font-weight: *([0-9]+).*/\1/p")
    style=$(echo "$block"  | sed -nE "s/.*font-style: *([a-z]+).*/\1/p")
    [ -z "$url" ] && continue
    [ -z "$style" ] && style=normal
    case "$url" in //*) dl="https:$url" ;; *) dl="$url" ;; esac
    file="${fam}-${weight}-${style}.woff2"
    if [ ! -s "$OUT/$file" ]; then curl -sL --max-time 60 -A "$UA" -o "$OUT/$file" "$dl"; fi
    printf "@font-face{font-family:'%s';src:url('./%s') format('woff2');font-weight:%s;font-style:%s;font-display:swap;}\n" \
      "$family" "$file" "$weight" "$style" >> "$CSS"
  done
  n=$(ls "$OUT" | grep -c "^${fam}-.*\.woff2$")
  echo "  ok $fam ($n faces)"
done

# --- Google Fonts (variable woff2 via modern UA) ---------------------------
GOOGLE=(
  "Instrument+Serif:ital@0;1"
  "Fraunces:opsz,wght@9..144,300..900"
  "Inter+Tight:wght@300..800"
  "JetBrains+Mono:wght@400;500"
  "DM+Serif+Display"
  "Bricolage+Grotesque:opsz,wght@12..96,300..800"
)

echo "==> Google Fonts"
for g in "${GOOGLE[@]}"; do
  raw=$(curl -sL --max-time 40 -A "$UA" "https://fonts.googleapis.com/css2?family=${g}&display=swap")
  [ -z "$raw" ] && { echo "  !! $g — no CSS"; continue; }
  name=$(echo "$g" | sed 's/[:+].*//;s/+/-/g' | tr 'A-Z' 'a-z')
  echo "/* --- $name (google) -------------------------------------------------- */" >> "$CSS"
  # Keep only latin subsets to stay small; rewrite urls to local files.
  echo "$raw" | tr '\n' ' ' | sed 's/@font-face/\n@font-face/g' | grep '@font-face' | while read -r block; do
    case "$block" in *"latin"*) : ;; *) continue ;; esac
    url=$(echo "$block" | grep -oE 'https://[^)]+\.woff2' | head -1)
    [ -z "$url" ] && continue
    file="gf-${name}-$(basename "$url")"
    [ -s "$OUT/$file" ] || curl -sL --max-time 60 -A "$UA" -o "$OUT/$file" "$url"
    echo "$block" | sed -E "s#url\(https://[^)]+\.woff2\)#url('./${file}')#" \
      | sed -E 's#/\*[^*]*\*/##g' >> "$CSS"
    echo >> "$CSS"
  done
  echo "  ok $name"
done

rm -f "$OUT"/_src-*.css
echo "==> done. $(ls "$OUT" | grep -c '\.woff2$') woff2 files, $(grep -c '@font-face' "$CSS") @font-face rules."
du -sh "$OUT"
